version: '3.9'

services:
  mysqldb:
    image: mysql:8.0
    healthcheck:
      test: "exit 0"
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
      - ignore:/usr/src/app/node_modules
    restart: always
    env_file: ./.env
    ports:
      - $API_PORT:8080
    stdin_open: true
    tty: true

volumes: 
  db:
  ignore: